<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'list_skin' => 'gallery',
  'head_line' => '',
  'new' => '',
  'thumb_w' => '',
  'thumb_h' => '',
  'thumb_d' => '',
  'item' => '4',
  'lg' => '4',
  'md' => '3',
  'sm' => '3',
  'xs' => '2',
  'color' => '',
  'cw' => '7',
  'cwlg' => '6',
  'cwmd' => '5',
  'cwsm' => '4',
  'cwxs' => '3',
  'bo_admin' => '',
  'noti_mb' => '',
  'na_crows' => '',
  'na_lucky_point' => '',
  'na_lucky_dice' => '',
  'na_gcancel' => '',
  'na_gtimes' => '',
  'na_shingo' => '',
  'xp_write' => '',
  'xp_comment' => '',
);
?>