<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  0 => 
  array (
    'text' => '뮤지아소개',
    'href' => 'https://muzia.net/content/company',
    'icon' => 'empty',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'bbs-content-company',
    'co_id' => 'company',
    's' => 
    array (
      0 => 
      array (
        'text' => '뮤지아소개',
        'href' => 'https://muzia.net/content/company',
        'icon' => 'fa fa-leaf',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-content-company',
        'co_id' => 'company',
      ),
      1 => 
      array (
        'text' => '공지사항',
        'href' => 'https://muzia.net/notice',
        'icon' => 'fa fa-bell-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-notice',
        'bo_table' => 'notice',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '히스토리',
        'href' => 'https://muzia.net/history',
        'icon' => 'fa fa-history',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-history',
        'bo_table' => 'history',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '뮤지아 유튜브',
        'href' => 'https://youtube.com/c/muzia',
        'icon' => 'fa fa-youtube-play',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '운영자블로그',
        'href' => '',
        'icon' => 'fa fa-github-alt',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
        's' => 
        array (
          0 => 
          array (
            'text' => '포트폴리오',
            'href' => 'https://sundo.kim',
            'icon' => 'fa fa-wordpress',
            'target' => '_blank',
            'line' => '',
            'sp' => '',
            'limit' => '',
            'grade' => 0,
            'id' => 'link',
          ),
          1 => 
          array (
            'text' => '블로그',
            'href' => 'https://computist.me',
            'icon' => 'fa fa-github',
            'target' => '_blank',
            'line' => '',
            'sp' => '',
            'limit' => '',
            'grade' => 0,
            'id' => 'link',
          ),
          2 => 
          array (
            'text' => '운영자 유튜브',
            'href' => 'https://youtube.com/c/muzia',
            'icon' => 'fa fa-youtube',
            'target' => '_blank',
            'line' => '',
            'sp' => '',
            'limit' => '',
            'grade' => 0,
            'id' => 'link',
          ),
        ),
      ),
    ),
  ),
  1 => 
  array (
    'text' => '토론 ·강좌',
    'href' => 'https://muzia.net/bbs/group.php?gr_id=forum',
    'icon' => 'fa fa-connectdevelop',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'bbs-group-forum',
    'gr_id' => 'forum',
    's' => 
    array (
      0 => 
      array (
        'text' => '토론(포럼)',
        'href' => 'https://muzia.net/qna',
        'icon' => 'fa fa-comments-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-qna',
        'bo_table' => 'qna',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '바이올린',
        'href' => 'https://muzia.net/violin',
        'icon' => 'fa fa-leanpub',
        'target' => '_self',
        'line' => '강의',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-violin',
        'bo_table' => 'violin',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '강의실',
        'href' => 'https://muzia.net/movie',
        'icon' => 'fa fa-google-wallet',
        'target' => '_self',
        'line' => '',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-movie',
        'bo_table' => 'movie',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  2 => 
  array (
    'text' => '음악게시판',
    'href' => 'https://muzia.net/music',
    'icon' => 'fa fa-music',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'bbs-board-music',
    'bo_table' => 'music',
    'wr_id' => NULL,
    'sca' => NULL,
  ),
  3 => 
  array (
    'text' => '자료실',
    'href' => 'https://muzia.net/bbs/group.php?gr_id=pds',
    'icon' => 'empty',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'bbs-group-pds',
    'gr_id' => 'pds',
    's' => 
    array (
      0 => 
      array (
        'text' => '자료실',
        'href' => 'https://muzia.net/pds',
        'icon' => 'fa fa-cloud-download',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-pds',
        'bo_table' => 'pds',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '악보자료실',
        'href' => 'https://muzia.net/sheet',
        'icon' => 'fa fa-file-pdf-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-sheet',
        'bo_table' => 'sheet',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '미디자료실',
        'href' => 'https://muzia.net/midi',
        'icon' => 'fa fa-music',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-midi',
        'bo_table' => 'midi',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
  4 => 
  array (
    'text' => '커뮤니티',
    'href' => 'https://muzia.net/bbs/group.php?gr_id=community',
    'icon' => 'empty',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'bbs-group-community',
    'gr_id' => 'community',
    's' => 
    array (
      0 => 
      array (
        'text' => '자유게시판',
        'href' => 'https://muzia.net/forum',
        'icon' => 'fa fa-comments-o',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-forum',
        'bo_table' => 'forum',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '가입인사',
        'href' => 'https://muzia.net/hello',
        'icon' => 'fa fa-child',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-hello',
        'bo_table' => 'hello',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '단골가게',
        'href' => 'https://muzia.net/store',
        'icon' => 'fa fa-asl-interpreting',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-store',
        'bo_table' => 'store',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
      3 => 
      array (
        'text' => '창조광장',
        'href' => 'https://muzia.net/creative',
        'icon' => 'fa fa-angellist',
        'target' => '_self',
        'line' => '',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => 'bbs-board-creative',
        'bo_table' => 'creative',
        'wr_id' => NULL,
        'sca' => NULL,
      ),
    ),
  ),
);
?>